### ISSUE TITLE
Problems with dollar ($) in arguments

### ISSUE THREAD

**Issue by jclin** [SharpeRAD/Cake.Powershell#3]
Heya, just wanted to give a heads up on an issue we encountered. We had an argument that contained a `$`. When wrapped in a `QuotedArgument`, Powershell sees the double-quoted string and tries to parse the $, and the characters following it, as a variable so the resulting string is incorrect.

What do you think of using [LiteralString](https://gist.github.com/jclin/41bf435658b6ea9dee14b2a8b6f6e7d9) in place of `QuotedArgument`? Since it's a single quoted string, Powershell would treat it as a string-literal, and that issue would be avoided.

**Comment by SharpeRAD** [comment]
I can see the need for a `LiteralString` argument but I want to be consistent with Cakes existing `IProcessArgument`. So instead of replacing `QuotedArgument`, how about submitting a PR that adds `LiteralStringArgument` and the necessary extension methods to `ProcessArgumentListExtensions`.

Sound like a good compromise?

**Comment by jclin** [comment]
Sounds good, I'll put up a PR in a bit.

**Comment by SharpeRAD** [comment]
Will be live in v0.2.4 in a few mins :smile:
