### ISSUE TITLE
Issues of executing remote script

### ISSUE THREAD

**Issue by bumbeishvili** [SharpeRAD/Cake.Powershell#7]
I am trying to execute  following `test.ps1` script  

    param([string]$name,[string]$password);
    write-Output "Hello $($name) my password is  $($password)";
    dir c:\
    New-Item c:\HRTemp\test.txt -ItemType file

on remote server using following command

    StartPowershellScript("Invoke-Command", args =>
    {
    	args.Append("ScriptBlock", "{{c:\\test.ps1 -name dato -password test}}" );
    });

I was able to successfully invoke this command from command line and now I want the same using cake script.  

I am using [Cake.Powershell](https://github.com/SharpeRAD/Cake.Powershell) addin.

When I try to execute it with one curly brace `{c:\\test.ps1 -name dato -password test}` ,   I am getting error:  

`Error: Input string was not in a correct format.`

When I try it with two curly brace   

`{{c:\\test.ps1 -name dato -password test}}`  

output is the following  

```Executing: Invoke-Command -ScriptBlock {{c:\test.ps1 -name dato -password test}}```

but, when I check on remote server test.txt file is not created.

Do you have any ideas why this is happening?

**Comment by SharpeRAD** [comment]
Please use "StartPowershellFile" over "StartPowershellScript" for script files.

**Comment by agc93** [comment]
@SharpeRAD in saying that, it's currently not possible to execute any command that uses a PowerShell ScriptBlock, since the curly braces get interpreted differently. Is it worth maybe including a setting to prevent echoing the command to the log?

**Comment by SharpeRAD** [comment]
[Like this?](https://github.com/SharpeRAD/Cake.Powershell/blob/master/src/Powershell/Runner/PowershellSettings.cs#L79)

**Comment by agc93** [comment]
No, I was getting at preventing [this]9https://github.com/SharpeRAD/Cake.Powershell/blob/master/src/Powershell/Runner/PowershellRunner.cs#L88) from executing. As it stands, including a curly brace is fine from an execution point of view, but the call to `ICakeLog` (at least in the case of `cake.exe` and its `CakeBuildLog` implementation) fails because the curly braces are implemented differently.

In saying that, I've just tested and using a module to replace the default `ICakeLog` implementation and the only way to get this to work is something along the lines of this (hacky) solution: 

```csharp
public void Write(Verbosity verbosity, LogLevel level, string format, params object[] args)
        {
            if (verbosity > Verbosity) return;
            _console.WriteLine(format.Contains("ScriptBlock") ? format.Replace("{", "{{").Replace("}", "}}") : format,
                args);
        }
```

Is it worth maybe changing that line in `PowerShellRunner` to double up any curly braces it finds since even `string.Format` will choke on them as-is?

**Comment by SharpeRAD** [comment]
Good call, PR away 😄 or I'll look at it tonight.

**Comment by agc93** [comment]
Done! #8 🍰

**Comment by bumbeishvili** [comment]
@SharpeRAD  How canI start powershell  script file on remote server? 

What is similar cake script to do the following

Invoke-Command HOST_NAME -ScriptBlock  { c:\\test.ps1 -name dato -password test }

I have tried 'StartPowershellFile' on local ps1 file with that content and got   
` error CS8000: This language feature ('Label in interactive') is not yet implemented in Roslyn`

**Comment by SharpeRAD** [comment]
I've updated the readme to include a remote file example, please be aware paths are relative to the server your running the script on, not from. Also checkout the troubleshooting section.

**Comment by bumbeishvili** [comment]
How can I pass parameters to that script?

**Comment by agc93** [comment]
@bumbeishvili as a workaround, note that your original solution (using `Invoke-Command` with `ScriptBlock` ) should work with Cake.Powershell version 0.2.7 since my PR is included in that version.

In saying that, I would defer to @SharpeRAD on `StartPowershellFile` being the "proper" way of doing it..

**Comment by bumbeishvili** [comment]
@agc93, @SharpeRAD   it worked, thanks both :+1: 

One issue left,  logs are not displaying , so It's really hard to debug

**Comment by SharpeRAD** [comment]
I updated the ReadMe again to include arguments for "StartPowershellFile".
